### ISSUE TITLE
Bundle is lacking mandatory keys

### ISSUE THREAD

**Issue by teeg82** [hlvnst/handlebars.tmbundle#1]
Just tried to install this bundle using the rename-zip approach, and received this message after double-clicking:

![screen shot 2015-05-26 at 1 08 48 pm](https://cloud.githubusercontent.com/assets/5384181/7818231/65a3d430-03a8-11e5-96f5-e20471861093.png)

I'm guessing the bundle is out of date, since the manual instructions point to what I believe is the old bundles directory (it should be `Avian/Pristine Copy/Bundles` I believe now).

**Comment by hlvnst** [comment]
Sorry for the delayed reply.

This is strange. I uninstalled the bundle, cloned a fresh copy from this repo, installed that one and it works fine. I don't know what could be going wrong on your end.

I believe you're right about the installation location, so I'll fix that momentarily.

**Comment by hlvnst** [comment]
I believe this should be fixed now.

**Comment by teeg82** [comment]
Also apologies for the delay. I actually changed jobs shortly after your reply and no longer using handlebars so I never got a chance to test this. I did this really quickly just now and it looks like it works.
